// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6boW3_p-wkrjUvCOFuk5W47_MastSPqE',
    appId: '1:387202563418:android:3efda3124aef3275ed8763',
    messagingSenderId: '387202563418',
    projectId: 'gesbuk-58f74',
    storageBucket: 'gesbuk-58f74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4UaRrePlWB1VIqH5GqsqUSome4NVMJWk',
    appId: '1:387202563418:ios:18fd4f7afd299967ed8763',
    messagingSenderId: '387202563418',
    projectId: 'gesbuk-58f74',
    storageBucket: 'gesbuk-58f74.appspot.com',
    androidClientId: '387202563418-5tfg08dkt7efbu6t783074r9io9u6dma.apps.googleusercontent.com',
    iosClientId: '387202563418-k1j6f448rp1n5d7upjhjgam6mcsa68iv.apps.googleusercontent.com',
    iosBundleId: 'com.gesbuk.user',
  );
}
